api_host: 'localhost'
domain: 'http://localhost:3011/'
hub_url: 'http://localhost:3011/'
website_url: 'http://localhost:3000/'
apphub_url: 'http://apphub.galacticexchange.io/'
#apphub_url: 'http://10.1.0.56:3000'

#
TEST_PHONE_NUMBER: "+380570000000"
TEST_USER_COUNTRY: "ua"
TEST_USER_PWD: "PH_GEX_PASSWD1"


#
ruby_user: 'mmx'


# first-level domain for our servers and clusters
domain_zone: 'gex'

# logs
log_async: 0

log_to_slack: 0
log_to_db: 0
log_to_kafka: 1


log_kafka_server_url: "log.devgex.net:9092"
log_kafka_topic: "test_log_app"

logs_elasticsearch_host: '51.0.0.63'
logs_elasticsearch_port: '9200'
logs_elasticsearch_prefix: ''




#
jwt_secret: '111122233344'


email_from: 'betanoreply@galacticexchange.io'
email_debug_catch_all: 'betauser@galacticexchange.io'


# elasticsearch
elasticsearch_host: '51.0.0.13'
elasticsearch_port: 9200
elasticsearch_prefix: 'gex_test.'





# provision
provision_use_provisioner: 1
provisioner_host: '51.0.0.55'
provisioner_port: 22
provisioner_user: 'root'
provisioner_pwd: 'PH_GEX_PASSWD1'


ansible_env: 'main'
dir_clusters_data: "/mount/ansibledata/"
provision_scripts_dir: '/mount/ansible/'
chef_dir: '/mount/chef-repo/'
server_app_repo: 'http://gex1.devgex.net:8090/applications'
server_app_repo_versions: 'http://gex1.devgex.net:8090/applications'



# redis
redis_host: '51.0.0.12'
redis_prefix: 'gex_test'


# rabbit
rabbit_host: 'rabbit.devgex.net'
rabbit_url: 'rabbit.devgex.net'
rabbit_api_endpoint: 'http://rabbit.devgex.net:15672'

rabbit_host_private: '51.0.0.22'
rabbit_url_private: '51.0.0.22'
rabbit_api_endpoint_private: 'http://51.0.0.22:15672'


rabbit_root_username: 'admin'
rabbit_root_password: 'PH_GEX_PASSWD1'
rabbit_prefix: 'gex_test'




# sensu
sensu_api_host: 'sensu.devgex.net'
sensu_api_host_private: 'sensu.devgex.net'
sensu_api_port: 4567
sensu_api_user: 'admin'
sensu_api_password: 'PH_GEX_PASSWD1'

rabbit_sensu_username: 'sensu'
rabbit_sensu_password: 'PH_GEX_PASSWD1'
rabbit_sensu_vhost: '/sensu'
rabbit_sensu_prefix: 'gex'


# kafka
counters_kafka_host: '51.0.0.72'
counters_kafka_prefix: 'gex'





# proxy
sshproxy_host: "proxy.gex"

# webproxy
webproxy_host: "webproxy.gex"


# openvpn
openvpn_host: '51.1.0.2'
#openvpn_ip6: 'FD9E:9E:9E:0:0:1:8:0/64'

# network
ip_client_base: 'FDE9:E9:E9'
ip_server_base: 'FD9E:9E:9E'


# containers
master_host: 'master.gex'

hadoop_master_ip_prefix: '51.77'
hue_master_ip_prefix: '51.78'
